sudo: required
services:
    - docker

before_install:
    - docker build -t pandeyvibhu/docker-angular -f Dockerfile.dev . 

script:
    - docker run -e CI=true -p 80:4200 pandeyvibhu/docker-angular npm run lint